### ISSUE TITLE
Change 'stockpile' to 'queue'

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#18]
Is 'stockpile' the best name for that thing?

I feel like 'display' and 'stockpile' is a mixed metaphor.

Perhaps display and _queue_?

Comments welcome.

**Comment by sethlbrown** [comment]
I definitely prefer queue, it makes more sense to me than stockpile.

On Tue, Aug 27, 2013 at 10:36 AM, Jeff Robbins notifications@github.comwrote:

> I feel like 'display' and 'stockpile' is a mixed metaphor.
> 
> Perhaps display and _queue_?
> 
> Comments welcome.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Lullabot/fliperoo/issues/18
> .

## 

Seth Brown
Director of Operations
Lullabot
seth@lullabot.com
c: 970-618-5370
w: 877.585.5226
http://lbt.me/seth
