### ISSUE TITLE
Create 2 additional icons for "Why Fliparoo" section

### ISSUE THREAD

**Issue by joshriggs** [Lullabot/fliparoo#35]

**Comment by joshriggs** [comment]
![tabs-icon-flexible](https://f.cloud.github.com/assets/2421980/1384336/b73dd808-3b4b-11e3-9bc1-989304f280d1.png)
![tabs-icon-more](https://f.cloud.github.com/assets/2421980/1384337/b753b61e-3b4b-11e3-8c83-0ef0b02b6d47.png)
![tabs-icon-responsive](https://f.cloud.github.com/assets/2421980/1384338/b7769a76-3b4b-11e3-8f12-b5948289ecde.png)

**Comment by jpamental** [comment]
Hey Josh - can you add them as SVG (or just put up an AI file?) I'm using an SVG/PNG fallback solution, so the vector stuff would be great. Thanks!

**Comment by joshriggs** [comment]
I built these in photoshop with a combo of vector and raster. I can rebuild them in Illustrator, but I'll need a bit longer to do that. They're currently 2x at 144dpi, so I think a standard PNG would suffice?

**Comment by jpamental** [comment]
I've already done the first one that way, so if you want to just post what you've got I can finish it up. I wanted to use the SVG where possible as much for 'completeness' as anything. I've got it set up so the PNG fallback works entirely within CSS, so it's a nice progressive enhancement.

Thanks!

Jason

Jason Pamental
principal & co-founder
h+w design

m: 401.743.4406
jason@hwdesignco.com
http://www.hwdesignco.com

Co-founder of the Responsive Bootcamp (http://www.responsivebootcamp.com/),  a one day workshop to learn responsive design.

**Comment by joshriggs** [comment]
Ahh. All the icons are within the master PSD, which should be currently updated on Dropbox. 
https://www.dropbox.com/s/vrgp36474qj9uur/fliparoo-mock.psd

Also, you can get all the other images I owe you in one convenient place, as well: 
https://www.dropbox.com/sh/uoim87juabx43n1/SWYir7YAX3

**Comment by jpamental** [comment]
Awesome -thanks!

Jason Pamental
principal & co-founder
h+w design

m: 401.743.4406
jason@hwdesignco.com
http://www.hwdesignco.com

Co-founder of the Responsive Bootcamp (http://www.responsivebootcamp.com/),  a one day workshop to learn responsive design.
