### ISSUE TITLE
Fliparoo perspective is cropped

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#38]
In @jpamental's current design, I'm seeing the perspective clipped on the kangaroo demo at the top of the page. I'm using Safari Mac.

You can see what's happening in the attached screen shot:

![fliparoo 2013-11-04 14-11-19](https://f.cloud.github.com/assets/321284/1467586/e3e89184-4584-11e3-8be0-7915801b5396.jpg)

You can slow down the animation to see this better. I haven't looked at the markup, but it might be fixed by setting overflow to visible on the surrounding div or perhaps adjusting the z-index on the Fliparoo element itself.

**Comment by jpamental** [comment]
Betting it's an overflow thing - I'll check it out!

J

**Comment by jpamental** [comment]
Fixed with the overflow: hidden change.
