### ISSUE TITLE
Left sidebar shifts right when it scrolls (position: fixed)

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#39]
The left sidebar is shifting about 10 pixels to the right when it becomes fixed and starts scrolling with the page. I'm on Safari Mac. See shots:

![fliparoo 2013-11-04 14-33-20](https://f.cloud.github.com/assets/321284/1467759/f7392426-4587-11e3-940f-782afee3e474.jpg)

![fliparoo 2013-11-04 14-34-46](https://f.cloud.github.com/assets/321284/1467775/2a6f280e-4588-11e3-9a4e-262b49a1c1ff.jpg)

**Comment by jpamental** [comment]
Yeah - that's a known one. Once it become's fixed, the percentages have to change for the width and I definitely have not chased down all the different breakpoint changes.

**Comment by jpamental** [comment]
Fixed it with the latest commit
