### ISSUE TITLE
We need more than 8 kangaroo images

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#40]
With 8 kangaroo images, we've got what amounts to 4 front images and 4 back images. The back side will always flip to the same image. Image 1 will always flip to image 4 and image 4 will always flip to image 1. It would be better to demo with a larger number of images to show how the tiles will flip to the next item in the queue, rather than just spinning around and and around.

I would like 12 images total. So we need 4 more kangaroo images.

**Comment by joshriggs** [comment]
4 new roos, commin' right up:
![kangaroo-flipper-10](https://f.cloud.github.com/assets/2421980/1666718/31e0771c-5c4b-11e3-8f23-b571391b34d9.png)
![kangaroo-flipper-9](https://f.cloud.github.com/assets/2421980/1666719/31e091d4-5c4b-11e3-837d-ed9a5f034a0f.png)
![kangaroo-flipper-11](https://f.cloud.github.com/assets/2421980/1666720/31e0d428-5c4b-11e3-88ea-12e16dafb6f1.png)
![kangaroo-flipper-12](https://f.cloud.github.com/assets/2421980/1666721/31f4b556-5c4b-11e3-862f-6a0675dddab5.png)

Also added to the project assets folder on Dropbox: https://www.dropbox.com/sh/uoim87juabx43n1/SWYir7YAX3

**Comment by jjeff** [comment]
Thanks @joshriggs! What do you think about #41? Should we stick some numbers on these images?

**Comment by joshriggs** [comment]
Yes, definitely! The design mock has the numbers. Looks like they dropped off somewhere in the shuffle.
