### ISSUE TITLE
Show numbers on the demo tiles on the main page

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#41]
Unfortunately the kangaroo images are too similar to one another and I don't think it's giving people enough of an idea of how _many_ images are being displayed. Adding numbers to the tiles would make it clear how many of them there are and the order in which they're being displayed.

**Comment by jjeff** [comment]
I suppose we could add the numbers to the images. That might be the easiest from a implementation demo standpoint.

**Comment by joshriggs** [comment]
The images should definitely have the numbers on each square, in white, as shown in the design mock.

**Comment by jpamental** [comment]
I think it might be pretty simple to make the images backgrounds and put the text back in there, but then we’ll have to do more finagling to set the sizes of each square in CSS, rather than letting it be defined by the image itself.

Simplest thing may be as Jeff suggested to just open them all up in Photoshop and add numerals. It’s not something that will change all that often so maybe that’s the lowest effort solution. Let me know what you think.

Jason

**Comment by joshriggs** [comment]
I'll add them to the images, at the behest of front-end development team :) I just assumed the numbers would be text, with the the kangaroos being background images. I supposed I probably should have clarified that earlier.

**Comment by jjeff** [comment]
Yeah, I'm inclined to add them to the images just because it will keep the demo simpler. People will look at it and think that it's images flipping around and it will be. If it were background images, then it would just be that much harder for people to grok.

**Comment by joshriggs** [comment]
@jpamental The updated images w/ numbers can be found here: https://www.dropbox.com/sh/uoim87juabx43n1/SWYir7YAX3

**Comment by jpamental** [comment]
Got ‘em - I’ll get them worked into the page tonight!

Jason

Jason Pamental
principal & co-founder
h+w design

m: 401.743.4406
jason@hwdesignco.com
http://www.hwdesignco.com

Co-founder of the Responsive Bootcamp (http://www.responsivebootcamp.com/),  a one day workshop to learn responsive design.

**Comment by jpamental** [comment]
New images are in, but the flip transition seems broken once it get's past 8 images (wait out the first 4 flips, then when the next ones flip, they disappear for a second and then the new image appears)

Wondering if there's been an update to the plugin portion that I'm missing?
