### ISSUE TITLE
In Chrome, only half of the images are clickable

### ISSUE THREAD

**Issue by mtift** [Lullabot/fliparoo#43]
In Google Chrome, only half of the images are clickable links -- that is, sometimes the left half is clickable and sometimes the right have is clickable. See, for example, the Robot images on http://lullabot.github.io/fliparoo.

In my testing on Windows, Ubuntu, and OSX, this is not an issue with IE or Firefox.

**Comment by mtift** [comment]
This also is an issue on OSX in Safari (so I would guess it's a webkit thing).

**Comment by jjeff** [comment]
I think this has something to do with the layering of `<a>` links in
Webkit. Fliparoo uses CSS to actually flip the elements in 3D space. When
you've got a link on the back side, I'm guessing that WebKit doesn't quite
know what to do with it.

My guess is that this is a Webkit bug. And/or a CSS-bug in our
implementation. Does this error show up on the Shoot examples page? It
might also be a bug in the way that Fliparoo is arranging the HTML/CSS. But
right now, Fliparoo isn't really doing much to rearrange things – or deal
with link tags in any special way.

**Comment by mtift** [comment]
This has been really tricky to troubleshoot.

I don't see any fliparoo happening in Shoot example pages I've seen, so I'm guessing I'm looking in the wrong place.

**Comment by mtift** [comment]
And yeah, I think this might not be a Fliparoo issue. I have been looking "upstream" at https://github.com/rstacruz/jquery.transit to see if I can replicate the behavior without Fliparoo.

**Comment by davereid** [comment]
Possibly related:
http://stackoverflow.com/questions/18514576/css-3d-transform-unable-to-click-link
http://stackoverflow.com/questions/15259726/css3-rotation-transition-causing-intermittent-mouse-click-detection
http://stackoverflow.com/questions/23548612/cant-click-on-buttons-after-css-transform

**Comment by rupl** [comment]
Are you setting z-index on the transformed elements? In my experience you can have weird stuff happen if you don't set z-index to be higher on the thing that is currently in front. This is also a super-easy way to provide a fallback for non-3D browsers.

I have a functional form (which is triggered by a link) on this page if you'd like to see what I'm talking about in action: http://css3playground.com/3d-flip-cards/

**Comment by mtift** [comment]
Thanks for your feeback, Chris! Yeah, I think we have the z-index set correctly [here](https://github.com/Lullabot/fliparoo/blob/master/fliparoo.css#L21), with the front set higher than the back.
